#DB_NAME: mydb
#DB_SERVER: localhost
#DB_PORT: 3306
#DB_USERNAME: myuser
#DB_PASSWORD: mypass

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_SERVER}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:p360_am;DB_CLOSE_DELAY=-1;MODE=MSSQLServer;INIT=CREATE SCHEMA IF NOT EXISTS DBO
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        default_catalog: demoDb
        default_schema: dbo
      javax.persistence.schema-generation.database.action: none